version: '3.8'

services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing_service
    ports:
      - "3224:80"  # Puerto local:contenedor
  dashboard_crm:
    build:
      context: ./frontend/dashboard-crm
      dockerfile: Dockerfile
    container_name: dashboard_service
    ports:
      - "4036:80"  # Puerto local:contenedor

